---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-cd-demo-production
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-cd-demo
  interval: 30s
  targetNamespace: production
  values:
    image:
      tag: 0.0.4
    replicaCount: 2

